name: Flutter Build CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Flutter Pub Get
      run: flutter pub get

    - name: Run Flutter Tests
      run: flutter test

    - name: Build APK (Android)
      if: matrix.os == 'ubuntu-latest'
      run: flutter build apk --debug

    - name: Build IPA (iOS)
      if: matrix.os == 'macos-latest'
      run: flutter build ios --debug --no-codesign
